package configgen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// containerdRegistry is the registry the pre-built hosts.toml applies to.
//
// Docker Hub only, and not by preference: this file is dropped into a directory
// named after the registry it configures, so a document covering ghcr.io would
// be a different file in a different directory. The panel generates the one
// that overlaps with what it can measure.
const containerdRegistry = "docker.io"

// containerdUpstream is the server containerd falls back to when no mirror
// answers. It is the registry the mirrors are mirrors of.
const containerdUpstream = "https://registry-1.docker.io"

// ContainerdHostsTOML renders a hosts.toml for containerd.
//
// The file belongs at <config_path>/docker.io/hosts.toml, where config_path is
// containerd's registry configuration directory — /etc/containerd/certs.d by
// convention, and the default in containerd 2.x. This layout is the one
// containerd 1.7 and later read; older releases used a mirrors table inside
// containerd's own config.toml, which the panel does not generate because
// emitting a fragment that has to be merged into a larger file by hand is a
// worse answer than saying so.
//
// Unlike daemon.json, TOML has comments. The header therefore carries the
// instructions, because a file that has to be placed in one exact directory is
// a file whose filename is not the whole story.
func ContainerdHostsTOML(mirrors []Mirror) (string, []Warning, error) {
	ranked, warnings := Select(mirrors)
	if len(ranked) == 0 {
		return "", warnings, ErrNoMirrors
	}

	var b strings.Builder

	b.WriteString("# Generated by MirrorPilot.\n")
	b.WriteString("#\n")
	b.WriteString("# Place this file at:\n")
	b.WriteString("#   <config_path>/" + containerdRegistry + "/hosts.toml\n")
	b.WriteString("#\n")
	b.WriteString("# config_path is containerd's registry configuration directory, by\n")
	b.WriteString("# convention /etc/containerd/certs.d. containerd 2.x uses that path by\n")
	b.WriteString("# default; on 1.7 and later, set it explicitly in containerd's config.toml.\n")
	b.WriteString("#\n")
	b.WriteString("# Mirrors are tried in the order they appear below.\n")
	b.WriteString("\n")

	fmt.Fprintf(&b, "server = %s\n", mustQuote(containerdUpstream))

	for _, m := range ranked {
		fmt.Fprintf(&b, "\n[host.%s]\n", mustQuote(m.Endpoint()))
		b.WriteString("  capabilities = [\"pull\", \"resolve\"]\n")
	}

	return b.String(), warnings, nil
}

// mustQuote encodes a string as a TOML basic string.
//
// encoding/json's string quoting and TOML's basic strings agree on the escapes
// that matter here (backslash, quote, and the control characters), so the
// encoder is reused rather than reimplemented. A mirror address is never going
// to need an escape, but "never" is how injection bugs are described
// afterwards.
func mustQuote(value string) string {
	raw, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("configgen: cannot quote %q: %v", value, err))
	}
	return string(raw)
}
